config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes/#{routes_name}.rb")))
  end

  devise_for :users, path_prefix: "devise", controllers: { registrations: "profiles" }

  devise_scope :user do
    scope "my" do
      put "profile", to: "profiles#update"
      patch "password", to: "passwords#update"
      patch "email", to: "profiles#update_email"
    end
  end

  draw :sidekiq
  draw :active_admin
  draw :api

  root "home#index"
  get "*path", to: "home#index", via: :all
end

app/views/shared/header/_tabs.html.erb
<div class="header bg-white border-b shadow-sm py-4 mb-6">
  <div class="container mx-auto flex flex-grow-1 px-4">
    <%= link_to "HackathonHoster", root_path, class: "text-2xl font-semibold hover:text-teal-600" %>
    <% navLinkStyle = "nav-link text-base text-gray-800 ml-6 hover:text-teal-600" %>
    <div class="flex ml-auto items-center">
      <div class="nav-item">
        <%= link_to "Features", "/features", class: navLinkStyle %>
      </div>
      <div class="nav-item">
        <%= link_to "Contact", "/contact", class: navLinkStyle %>
      </div>
      <% if user_signed_in? %>
        <%= render "shared/header/user_is_signed_in" %>
      <% else %>
        <div class="nav-item">
          <%= link_to "Sign In", new_session_path(:user), class: navLinkStyle %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/header/_user_is_signed_in.html.erb
<% navLinkStyle = "nav-link text-base text-gray-800 flex items-center hover:text-teal-600 focus:outline-none" %>
<% drodownLinkStyle = "rounded-t hover:bg-gray-200 hover:text-gray-800 py-2 px-4 block whitespace-no-wrap" %>
<div class="dropdown inline-block relative ml-6">
  <button data-behavior="dropdown-toggle" class="<%= navLinkStyle %>">
    <div class="mr-1"><%= current_user.name %></div>
    <svg class="fill-current h-4 w-4" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20"><path d="M9.293 12.95l.707.707L15.657 8l-1.414-1.414L10 10.828 5.757 6.586 4.343 8z" /> </svg>
  </button>
  <div class="overflow-hidden hidden" data-behavior="dropdown-menu">
    <div class="dropdown-overlay bg-transparent top-0 left-0 w-full h-full fixed z-10" data-behavior="dropdown-toggle"></div>
    <ul class="dropdown-menu bg-white shadow-md border absolute right-0 text-gray-700 pt-1 mt-2 rounded-md z-20">
      <% if super_admin_signed_in? %>
        <li>
          <%= link_to "Active Admin", active_admin_root_path, class: drodownLinkStyle %>
        </li>
        <li>
          <%= link_to "Sidekiq", sidekiq_web_path, "target" => "_blank", class: drodownLinkStyle %>
        </li>
      <% end %>
      <li>
        <%= link_to "My Account", profile_path, class: drodownLinkStyle %>
      </li>
      <li>
        <%= link_to "Change Password", password_edit_path, class: drodownLinkStyle %>
      </li>
      <li>
        <%= link_to "Logout", logout_path, class: drodownLinkStyle %>
      </li>
    </ul>
  </div>
</div>